------------------- Group 1 Product -----------------------
DELETE FROM PRODUCT WHERE GROUP_ID = 1;

INSERT INTO PRODUCT VALUES (16, 1, "Butter, whipped");
INSERT INTO PRODUCT VALUES (17, 1, "Butter oil, anhydrous");
INSERT INTO PRODUCT VALUES (18, 1, "Cheese, blue");
INSERT INTO PRODUCT VALUES (19, 1, "Cheese, brick");
INSERT INTO PRODUCT VALUES (20, 1, "Cheese, brie");
INSERT INTO PRODUCT VALUES (21, 1, "Cheese, camembert");
INSERT INTO PRODUCT VALUES (22, 1, "Cheese, caraway");
INSERT INTO PRODUCT VALUES (23, 1, "Cheese, cheshire");
INSERT INTO PRODUCT VALUES (24, 1, "Cheese, colby");
INSERT INTO PRODUCT VALUES (25, 1, "Cheese, cottage, creamed (4.5% M.F.)");
INSERT INTO PRODUCT VALUES (26, 1, "Cheese, cottage, creamed with fruit");
INSERT INTO PRODUCT VALUES (27, 1, "Cheese, cottage, uncreamed, dry curd (0.4% M.F.)");
INSERT INTO PRODUCT VALUES (28, 1, "Cheese, cream");
INSERT INTO PRODUCT VALUES (29, 1, "Cheese, edam");
INSERT INTO PRODUCT VALUES (30, 1, "Cheese, fontina");
INSERT INTO PRODUCT VALUES (31, 1, "Cheese, gjetost");
INSERT INTO PRODUCT VALUES (32, 1, "Cheese, gruyere");
INSERT INTO PRODUCT VALUES (33, 1, "Cheese, limburger");
INSERT INTO PRODUCT VALUES (34, 1, "Cheese, monterey");
INSERT INTO PRODUCT VALUES (35, 1, "Cheese, mozzarella, (48% water, 25% M.F.)");
INSERT INTO PRODUCT VALUES (37, 1, "Cheese, muenster");
INSERT INTO PRODUCT VALUES (38, 1, "Cheese, neufchatel");
INSERT INTO PRODUCT VALUES (39, 1, "Cheese, parmesan, dry grated");
INSERT INTO PRODUCT VALUES (40, 1, "Cheese, parmesan, hard");
INSERT INTO PRODUCT VALUES (41, 1, "Cheese, port-salut");
INSERT INTO PRODUCT VALUES (42, 1, "Cheese, provolone");
INSERT INTO PRODUCT VALUES (43, 1, "Cheese, ricotta, with whole milk");
INSERT INTO PRODUCT VALUES (44, 1, "Cheese, ricotta, with partly skimmed milk");
INSERT INTO PRODUCT VALUES (45, 1, "Cheese, romano");
INSERT INTO PRODUCT VALUES (46, 1, "Cheese, roquefort (blue)");
INSERT INTO PRODUCT VALUES (47, 1, "Cheese, swiss (emmental)");
INSERT INTO PRODUCT VALUES (48, 1, "Cheese, tilsit, with whole milk");
INSERT INTO PRODUCT VALUES (51, 1, "Cheese, processed, cheddar, cold pack");
INSERT INTO PRODUCT VALUES (52, 1, "Cheese, processed food, swiss, loaf");
INSERT INTO PRODUCT VALUES (54, 1, "Cream, whipped, cream topping, pressurized");
INSERT INTO PRODUCT VALUES (55, 1, "Eggnog, 7% M.F., Canadian product, 4% to 8% M.F.");
INSERT INTO PRODUCT VALUES (56, 1, "Coffee whitener (non dairy), liquid");
INSERT INTO PRODUCT VALUES (57, 1, "Dessert topping (non dairy), powdered");
INSERT INTO PRODUCT VALUES (58, 1, "Dessert topping (non dairy), powdered, prepared with whole milk");
INSERT INTO PRODUCT VALUES (59, 1, "Dessert topping (non dairy), pressurized");
INSERT INTO PRODUCT VALUES (60, 1, "Dessert topping (non dairy), frozen, semisolid");
INSERT INTO PRODUCT VALUES (61, 1, "Milk, fluid, partly skimmed, 2% M.F.");
INSERT INTO PRODUCT VALUES (63, 1, "Milk, fluid, partly skimmed, 1% M.F.");
INSERT INTO PRODUCT VALUES (66, 1, "Milk, dry whole");
INSERT INTO PRODUCT VALUES (67, 1, "Milk, dry, buttermilk, sweet cream");
INSERT INTO PRODUCT VALUES (68, 1, "Milk, condensed, sweetened, canned");
INSERT INTO PRODUCT VALUES (69, 1, "Milk, fluid, chocolate, whole");
INSERT INTO PRODUCT VALUES (70, 1, "Milk, fluid, chocolate, partly skimmed, 2% M.F.");
INSERT INTO PRODUCT VALUES (72, 1, "Milk, fluid, goat, enriched, whole");
INSERT INTO PRODUCT VALUES (73, 1, "Milk, fluid, human (breast milk), mature");
INSERT INTO PRODUCT VALUES (74, 1, "Milk, fluid, sheep, whole");
INSERT INTO PRODUCT VALUES (77, 1, "Whey, acid, fluid");
INSERT INTO PRODUCT VALUES (78, 1, "Whey, acid, dry");
INSERT INTO PRODUCT VALUES (79, 1, "Whey, sweet, fluid");
INSERT INTO PRODUCT VALUES (80, 1, "Whey, sweet, dry");
INSERT INTO PRODUCT VALUES (83, 1, "Egg, chicken, dried, whole");
INSERT INTO PRODUCT VALUES (84, 1, "Egg, chicken, dried, whole, stabilized");
INSERT INTO PRODUCT VALUES (85, 1, "Egg, chicken, white, pan dried, flakes");
INSERT INTO PRODUCT VALUES (86, 1, "Egg, chicken, white, dried, powder, glucose reduced");
INSERT INTO PRODUCT VALUES (87, 1, "Egg, chicken, yolk, dried");
INSERT INTO PRODUCT VALUES (88, 1, "Egg, duck, whole, fresh, raw");
INSERT INTO PRODUCT VALUES (89, 1, "Egg, goose, whole, fresh, raw");
INSERT INTO PRODUCT VALUES (90, 1, "Egg, quail, whole, fresh, raw");
INSERT INTO PRODUCT VALUES (91, 1, "Egg, turkey, whole, fresh, raw");
INSERT INTO PRODUCT VALUES (92, 1, "Butter, unsalted");
INSERT INTO PRODUCT VALUES (93, 1, "Cheese, parmesan, shredded");
INSERT INTO PRODUCT VALUES (96, 1, "Cheese, goat, hard, (less than 35% water, 36% M.F.)");
INSERT INTO PRODUCT VALUES (97, 1, "Cheese, goat, semi-soft, (35% to 55% water, 30% M.F.)");
INSERT INTO PRODUCT VALUES (98, 1, "Cheese, goat, soft, (more than 55% water, 21% M.F.)");
INSERT INTO PRODUCT VALUES (100, 1, "Cheese fondue");

--------------------- Group 9 Product -----------------------
DELETE FROM PRODUCT WHERE GROUP_ID = 9;

INSERT INTO PRODUCT VALUES (1484, 9,  "Acerola (West Indian cherry), raw");
INSERT INTO PRODUCT VALUES (1485, 9,  "Acerola juice, raw");
INSERT INTO PRODUCT VALUES (1486, 9,  "Apple, raw, without skin, sliced, cooked, microwaved");
INSERT INTO PRODUCT VALUES (1487, 9,  "Apple, canned, sweetened, sliced, heated");
INSERT INTO PRODUCT VALUES (1488, 9,  "Apple, dehydrated (low moisture), sulphured, uncooked");
INSERT INTO PRODUCT VALUES (1489, 9,  "Apple, dehydrated (low moisture), sulphured, cooked");
INSERT INTO PRODUCT VALUES (1490, 9,  "Apple, dried, sulphured, uncooked");
INSERT INTO PRODUCT VALUES (1491, 9,  "Apple, dried, sulphured, stewed, no added sugar");
INSERT INTO PRODUCT VALUES (1492, 9,  "Apple, dried, sulphured, stewed, added sugar");
INSERT INTO PRODUCT VALUES (1493, 9,  "Apple, frozen, sliced, unsweetened, unheated");
INSERT INTO PRODUCT VALUES (1494, 9,  "Apple, frozen, sliced, unsweetened, heated");
INSERT INTO PRODUCT VALUES (1495, 9,  "Apple juice, canned or bottled, without added vitamin C");
INSERT INTO PRODUCT VALUES (1496, 9,  "Apple juice, frozen concentrate, undiluted, without vitamin C");
INSERT INTO PRODUCT VALUES (1497, 9,  "Apple juice, frozen concentrate, diluted, without added vitamin C");
INSERT INTO PRODUCT VALUES (1498, 9,  "Apricot, raw");
INSERT INTO PRODUCT VALUES (1499, 9,  "Apricot, canned halves with skin, water pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1500, 9,  "Apricot, canned whole no skin, water pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1501, 9,  "Apricot, canned halves with skin, juice pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1502, 9,  "Apricot, canned halves with skin, extra light syrup, solids and liquid");
INSERT INTO PRODUCT VALUES (1503, 9,  "Apricot, canned halves with skin, light syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1504, 9,  "Apricot, canned halves with skin, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1505, 9,  "Apricot, canned whole no skin, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1506, 9,  "Apricot, canned whole no skin, extra heavy syrup, solids and liquid");
INSERT INTO PRODUCT VALUES (1507, 9,  "Apricot, dried, sulphured, uncooked");
INSERT INTO PRODUCT VALUES (1508, 9,  "Apricot, dried, sulphured, cooked without added sugar");
INSERT INTO PRODUCT VALUES (1509, 9,  "Apricot, dried, sulphured, cooked, added sugar");
INSERT INTO PRODUCT VALUES (1510, 9,  "Apricot, frozen, sweetened");
INSERT INTO PRODUCT VALUES (1511, 9,  "Avocado, raw, all commercial varieties");
INSERT INTO PRODUCT VALUES (1512, 9,  "Avocado, raw, california");
INSERT INTO PRODUCT VALUES (1513, 9,  "Avocado, raw, florida");
INSERT INTO PRODUCT VALUES (1514, 9,  "Banana, dehydrated or banana powder");
INSERT INTO PRODUCT VALUES (1515, 9,  "Blackberry, raw");
INSERT INTO PRODUCT VALUES (1516, 9,  "Blackberry, canned, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1517, 9,  "Blackberry, frozen, unsweetened");
INSERT INTO PRODUCT VALUES (1518, 9,  "Blueberry, canned, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1519, 9,  "Blueberry, frozen, sweetened");
INSERT INTO PRODUCT VALUES (1520, 9,  "Boysenberry, canned, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1521, 9,  "Boysenberry, frozen, unsweetened");
INSERT INTO PRODUCT VALUES (1522, 9,  "Breadfruit, raw");
INSERT INTO PRODUCT VALUES (1523, 9,  "Carambola (star fruit), raw");
INSERT INTO PRODUCT VALUES (1524, 9,  "Carissa (natalplum), raw");
INSERT INTO PRODUCT VALUES (1525, 9,  "Cherimoya, raw");
INSERT INTO PRODUCT VALUES (1526, 9,  "Cherry, sour, red, raw");
INSERT INTO PRODUCT VALUES (1527, 9,  "Cherry, sour, red, canned, water pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1528, 9,  "Cherry, sour, red, canned, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1529, 9,  "Cherry, sour, red, canned, extra heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1530, 9,  "Cherry sour, red, frozen, unsweetened");
INSERT INTO PRODUCT VALUES (1531, 9,  "Cherry, sweet, raw");
INSERT INTO PRODUCT VALUES (1532, 9,  "Cherry, sweet, canned, water pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1533, 9,  "Cherry, sweet, canned, juice pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1534, 9,  "Cherry, sweet, canned, heavy syrup pack");
INSERT INTO PRODUCT VALUES (1535, 9,  "Cherry, sweet, canned, extra heavy syrup pack");
INSERT INTO PRODUCT VALUES (1536, 9,  "Cherry, sweet, frozen, sweetened");
INSERT INTO PRODUCT VALUES (1537, 9,  "Crabapple, raw");
INSERT INTO PRODUCT VALUES (1538, 9,  "Cranberry, raw");
INSERT INTO PRODUCT VALUES (1539, 9,  "Sauce, cranberry, canned, sweetened");
INSERT INTO PRODUCT VALUES (1540, 9,  "Cranberry orange relish, canned");
INSERT INTO PRODUCT VALUES (1541, 9,  "Currant, european black, raw");
INSERT INTO PRODUCT VALUES (1542, 9,  "Currant, zante, dried");
INSERT INTO PRODUCT VALUES (1543, 9,  "Custard-apple, raw");
INSERT INTO PRODUCT VALUES (1544, 9,  "Elderberry, raw");
INSERT INTO PRODUCT VALUES (1545, 9,  "Fig, canned, water pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1546, 9,  "Fig, canned, light syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1547, 9,  "Fig, canned, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1548, 9,  "Fig, canned, extra heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1549, 9,  "Fig, dried, uncooked");
INSERT INTO PRODUCT VALUES (1550, 9,  "Fig, dried, cooked");
INSERT INTO PRODUCT VALUES (1551, 9,  "Fruit cocktail (peach, pear, apricot, pineapple, cherry, grape), canned, water pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1552, 9,  "Fruit cocktail (peach, pear, apricot, pineapple, cherry, grape), canned, juice pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1553, 9,  "Fruit cocktail (peach, pear, apricot, pineapple, cherry, grape), canned, extra light syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1554, 9,  "Fruit cocktail (peach, pear, apricot, pineapple, cherry, grape), canned, light syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1555, 9,  "Fruit cocktail (peach, pear, apricot, pineapple, cherry, grape), canned, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1556, 9,  "Fruit cocktail (peach, pear, apricot, pineapple, cherry, grape), canned, extra heavy syrup, solids and liquid");
INSERT INTO PRODUCT VALUES (1557, 9,  "Fruit salad (peach, pear, apricot, pineapple, cherry), canned, water pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1558, 9,  "Fruit salad (peach, pear, apricot, pineapple, cherry), canned, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1559, 9,  "Fruit salad (peach, pear, apricot, pineapple, cherry), canned, extra heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1560, 9,  "Gooseberry raw");
INSERT INTO PRODUCT VALUES (1561, 9,  "Gooseberry, canned, light syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1562, 9,  "Grapefruit, pink or red, all areas, raw");
INSERT INTO PRODUCT VALUES (1563, 9,  "Grapefruit, pink or red, california or arizona, raw");
INSERT INTO PRODUCT VALUES (1564, 9,  "Grapefruit, pink or red, florida, raw");
INSERT INTO PRODUCT VALUES (1565, 9,  "Grapefruit, white, california, raw");
INSERT INTO PRODUCT VALUES (1566, 9,  "Grapefruit, white, florida, raw");
INSERT INTO PRODUCT VALUES (1567, 9,  "Grapefruit, canned, waterpack, solids and liquid");
INSERT INTO PRODUCT VALUES (1568, 9,  "Grapefruit, canned, juice pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1569, 9,  "Grapefruit, canned, light syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1570, 9,  "Grapefruit juice, canned, sweetened");
INSERT INTO PRODUCT VALUES (1571, 9,  "Grapefruit juice, frozen concentrate, undiluted");
INSERT INTO PRODUCT VALUES (1572, 9,  "Grapefruit juice, white, raw");
INSERT INTO PRODUCT VALUES (1573, 9,  "Grape, North American type (slip skin), raw");
INSERT INTO PRODUCT VALUES (1574, 9,  "Grape, thompson seedless, canned, water pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1575, 9,  "Grape, thompson seedless, canned, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1576, 9,  "Grape juice, canned or bottled, without added vitamin C");
INSERT INTO PRODUCT VALUES (1577, 9,  "Groundcherry, raw");
INSERT INTO PRODUCT VALUES (1578, 9,  "Guava, common, raw");
INSERT INTO PRODUCT VALUES (1579, 9,  "Guava, strawberry, raw");
INSERT INTO PRODUCT VALUES (1580, 9,  "Guava sauce, cooked");
INSERT INTO PRODUCT VALUES (1581, 9,  "Jackfruit, raw");
INSERT INTO PRODUCT VALUES (1582, 9,  "Java-plum, raw");
INSERT INTO PRODUCT VALUES (1583, 9,  "Jujube (chinese date), raw");
INSERT INTO PRODUCT VALUES (1584, 9,  "Jujube (chinese date), dried");
INSERT INTO PRODUCT VALUES (1585, 9,  "Kiwi fruit, raw");
INSERT INTO PRODUCT VALUES (1586, 9,  "Kumquat, raw");
INSERT INTO PRODUCT VALUES (1587, 9,  "Lemon, raw, without peel");
INSERT INTO PRODUCT VALUES (1589, 9,  "Lemon juice, raw");
INSERT INTO PRODUCT VALUES (1590, 9,  "Lemon juice, canned or bottled");
INSERT INTO PRODUCT VALUES (1591, 9,  "Lemon juice, frozen");
INSERT INTO PRODUCT VALUES (1592, 9,  "Lemon peel, raw");
INSERT INTO PRODUCT VALUES (1593, 9,  "Lime, raw");
INSERT INTO PRODUCT VALUES (1594, 9,  "Lime juice, raw");
INSERT INTO PRODUCT VALUES (1595, 9,  "Lime juice, canned or bottled");
INSERT INTO PRODUCT VALUES (1596, 9,  "Lychee (litchi), raw");
INSERT INTO PRODUCT VALUES (1597, 9,  "Lychee, dried");
INSERT INTO PRODUCT VALUES (1598, 9,  "Loganberry, frozen");
INSERT INTO PRODUCT VALUES (1599, 9,  "Longan, raw");
INSERT INTO PRODUCT VALUES (1600, 9,  "Longan, dried");
INSERT INTO PRODUCT VALUES (1601, 9,  "Loquat, raw");
INSERT INTO PRODUCT VALUES (1602, 9,  "Mammy-apple, raw");
INSERT INTO PRODUCT VALUES (1603, 9,  "Mango, raw");
INSERT INTO PRODUCT VALUES (1604, 9,  "Melon, casaba, raw");
INSERT INTO PRODUCT VALUES (1605, 9,  "Melon, honeydew, raw");
INSERT INTO PRODUCT VALUES (1606, 9,  "Melon balls, frozen (cantaloupe and honeydew)");
INSERT INTO PRODUCT VALUES (1610, 9,  "Mulberry, raw");
INSERT INTO PRODUCT VALUES (1611, 9,  "Nectarine, raw");
INSERT INTO PRODUCT VALUES (1612, 9,  "Oheloberry, raw");
INSERT INTO PRODUCT VALUES (1613, 9,  "Olive, ripe, canned, small to extra large");
INSERT INTO PRODUCT VALUES (1614, 9,  "Olive, ripe, canned, jumbo to super colossal");
INSERT INTO PRODUCT VALUES (1615, 9,  "Orange, california, valencia, raw");
INSERT INTO PRODUCT VALUES (1616, 9,  "Orange, california, navel, raw");
INSERT INTO PRODUCT VALUES (1617, 9,  "Orange, florida, raw");
INSERT INTO PRODUCT VALUES (1618, 9,  "Orange, with peel, raw");
INSERT INTO PRODUCT VALUES (1619, 9,  "Orange juice, raw");
INSERT INTO PRODUCT VALUES (1620, 9,  "Orange juice, chilled, includes from concentrate");
INSERT INTO PRODUCT VALUES (1621, 9,  "Orange peel, raw");
INSERT INTO PRODUCT VALUES (1622, 9,  "Orange grapefruit juice, canned");
INSERT INTO PRODUCT VALUES (1623, 9,  "Tangerine (mandarin), raw");
INSERT INTO PRODUCT VALUES (1624, 9,  "Tangerine (mandarin) juice, raw");
INSERT INTO PRODUCT VALUES (1625, 9,  "Tangerine (mandarin) juice, canned, sugar added");
INSERT INTO PRODUCT VALUES (1628, 9,  "Papaya, raw");
INSERT INTO PRODUCT VALUES (1629, 9,  "Papaya nectar, canned");
INSERT INTO PRODUCT VALUES (1630, 9,  "Passion fruit, purple, raw");
INSERT INTO PRODUCT VALUES (1631, 9,  "Passion fruit juice, purple, raw");
INSERT INTO PRODUCT VALUES (1632, 9,  "Passion fruit juice, yellow, raw");
INSERT INTO PRODUCT VALUES (1633, 9,  "Peach, canned halves or slices, juice pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1634, 9,  "Peach, canned halves or slices, extra light syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1635, 9,  "Peach, canned halves or slices, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1636, 9,  "Peach, canned halves or slices, extra heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1637, 9,  "Peach, spiced, canned whole, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1638, 9,  "Peach, dehydrated (low moisture), sulphured, uncooked");
INSERT INTO PRODUCT VALUES (1639, 9,  "Peach, dehydrated (low moisture), sulphured, cooked");
INSERT INTO PRODUCT VALUES (1640, 9,  "Peach, dried halves, sulphured, uncooked");
INSERT INTO PRODUCT VALUES (1641, 9,  "Peach, dried halves, sulphured, cooked, no added sugar");
INSERT INTO PRODUCT VALUES (1642, 9,  "Peach, dried halves, sulphured, cooked, added sugar");
INSERT INTO PRODUCT VALUES (1643, 9,  "Peach, frozen sliced, sweetened");
INSERT INTO PRODUCT VALUES (1644, 9,  "Peach nectar, canned");
INSERT INTO PRODUCT VALUES (1645, 9,  "Pear, canned halves, juice pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1646, 9,  "Pear, canned, halves, extra light syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1647, 9,  "Pear, canned halves, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1648, 9,  "Pear, canned halves, extra heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1649, 9,  "Pear, dried halves, sulphured, uncooked");
INSERT INTO PRODUCT VALUES (1650, 9,  "Pear, dried halves, sulphured, cooked, no added sugar");
INSERT INTO PRODUCT VALUES (1651, 9,  "Pear, dried halves, sulphured, cooked, added sugar");
INSERT INTO PRODUCT VALUES (1652, 9,  "Pear nectar, canned");
INSERT INTO PRODUCT VALUES (1653, 9,  "Persimmon, japanese, raw");
INSERT INTO PRODUCT VALUES (1654, 9,  "Persimmon, japanese, dried");
INSERT INTO PRODUCT VALUES (1655, 9,  "Persimmon, native, raw");
INSERT INTO PRODUCT VALUES (1656, 9,  "Pineapple, frozen chunks, sweetened");
INSERT INTO PRODUCT VALUES (1657, 9,  "Pineapple juice, canned, added vitamin C");
INSERT INTO PRODUCT VALUES (1658, 9,  "Pineapple juice, frozen concentrate, unsweetened, undiluted");
INSERT INTO PRODUCT VALUES (1659, 9,  "Pineapple juice, frozen concentrate, diluted");
INSERT INTO PRODUCT VALUES (1660, 9,  "Pitanga, raw");
INSERT INTO PRODUCT VALUES (1661, 9,  "Plantain, raw");
INSERT INTO PRODUCT VALUES (1662, 9,  "Plantain, cooked");
INSERT INTO PRODUCT VALUES (1663, 9,  "Plum, canned, purple, water pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1664, 9,  "Plum, canned, purple, juice pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1665, 9,  "Plum, canned, purple, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1666, 9,  "Plum, canned, purple, extra heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1667, 9,  "Pomegranate, raw");
INSERT INTO PRODUCT VALUES (1668, 9,  "Prickly pear, raw");
INSERT INTO PRODUCT VALUES (1669, 9,  "Prune, canned, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1670, 9,  "Prune, dehydrated (low moisture), uncooked");
INSERT INTO PRODUCT VALUES (1671, 9,  "Prune, dehydrated (low moisture), cooked");
INSERT INTO PRODUCT VALUES (1672, 9,  "Prune, dried, cooked, added sugar");
INSERT INTO PRODUCT VALUES (1673, 9,  "Prune juice, canned");
INSERT INTO PRODUCT VALUES (1674, 9,  "Pummelo, raw");
INSERT INTO PRODUCT VALUES (1675, 9,  "Quince, raw");
INSERT INTO PRODUCT VALUES (1676, 9,  "Raspberry, canned, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1677, 9,  "Raspberry, frozen, sweetened");
INSERT INTO PRODUCT VALUES (1678, 9,  "Rhubarb, frozen, uncooked");
INSERT INTO PRODUCT VALUES (1679, 9,  "Rhubarb, frozen, cooked, added sugar");
INSERT INTO PRODUCT VALUES (1680, 9,  "Roselle, raw");
INSERT INTO PRODUCT VALUES (1681, 9,  "Rose-apple, raw");
INSERT INTO PRODUCT VALUES (1682, 9,  "Sapodilla, raw");
INSERT INTO PRODUCT VALUES (1683, 9,  "Sapote, mamey, raw");
INSERT INTO PRODUCT VALUES (1684, 9,  "Soursop, raw");
INSERT INTO PRODUCT VALUES (1685, 9,  "Strawberry, canned, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1686, 9,  "Strawberry, frozen, sweetened, whole");
INSERT INTO PRODUCT VALUES (1687, 9,  "Strawberry, frozen, sweetened, sliced");
INSERT INTO PRODUCT VALUES (1688, 9,  "Sugar-apple, raw");
INSERT INTO PRODUCT VALUES (1689, 9,  "Tamarind, raw");
INSERT INTO PRODUCT VALUES (1690, 9,  "Fruit salad, tropical (pineapple, red and yellow papaya), canned, heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1691, 9,  "Watermelon, raw");
INSERT INTO PRODUCT VALUES (1692, 9,  "Feijoa, raw");
INSERT INTO PRODUCT VALUES (1693, 9,  "Pear, asian, raw");
INSERT INTO PRODUCT VALUES (1694, 9,  "Apricot nectar, canned");
INSERT INTO PRODUCT VALUES (1696, 9,  "Apple, raw, with skin");
INSERT INTO PRODUCT VALUES (1697, 9,  "Apple, raw, without skin");
INSERT INTO PRODUCT VALUES (1698, 9,  "Apple, raw, without skin, sliced, cooked, boiled");
INSERT INTO PRODUCT VALUES (1699, 9,  "Apple, canned, sweetened, sliced, unheated");
INSERT INTO PRODUCT VALUES (1700, 9,  "Applesauce, canned, unsweetened");
INSERT INTO PRODUCT VALUES (1701, 9,  "Applesauce, canned, sweetened");
INSERT INTO PRODUCT VALUES (1702, 9,  "Apricots, dehydrated (low moisture), sulphured, uncooked");
INSERT INTO PRODUCT VALUES (1703, 9,  "Apricot, dehydrated (low moisture), sulphured, cooked");
INSERT INTO PRODUCT VALUES (1704, 9,  "Banana, raw");
INSERT INTO PRODUCT VALUES (1705, 9,  "Blueberry, raw");
INSERT INTO PRODUCT VALUES (1706, 9,  "Blueberry, frozen, unsweetened");
INSERT INTO PRODUCT VALUES (1707, 9,  "Cherry, sour, red, canned, light syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1708, 9,  "Cherry, sweet, canned, light syrup pack");
INSERT INTO PRODUCT VALUES (1709, 9,  "Currant, red and white, raw");
INSERT INTO PRODUCT VALUES (1710, 9,  "Date, domestic, natural and dry");
INSERT INTO PRODUCT VALUES (1711, 9,  "Fig, raw");
INSERT INTO PRODUCT VALUES (1712, 9,  "Fruit salad (peach, pear, apricot, pineapple, cherry), canned, juice pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1713, 9,  "Fruit salad (peach, pear, apricot, pineapple, cherry), canned, light syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1714, 9,  "Grapefruit, pink, red or white, all areas, raw");
INSERT INTO PRODUCT VALUES (1715, 9,  "Grapefruit, white, all areas, raw");
INSERT INTO PRODUCT VALUES (1716, 9,  "Grapefruit juice, canned, no added sugar");
INSERT INTO PRODUCT VALUES (1717, 9,  "Grapefruit juice, frozen concentrate, diluted");
INSERT INTO PRODUCT VALUES (1718, 9,  "Grape, red or green (European type, such as Thompson seedless), adherent skin, raw");
INSERT INTO PRODUCT VALUES (1719, 9,  "Grape juice, frozen concentrate, sugar and vitamin C added, undiluted");
INSERT INTO PRODUCT VALUES (1720, 9,  "Grape juice, frozen concentrate, sugar and vitamin C added, diluted");
INSERT INTO PRODUCT VALUES (1721, 9,  "Melon, cantaloupe, raw");
INSERT INTO PRODUCT VALUES (1722, 9,  "Orange, all commercial varieties, raw");
INSERT INTO PRODUCT VALUES (1723, 9,  "Orange juice, canned");
INSERT INTO PRODUCT VALUES (1724, 9,  "Orange juice, frozen concentrate, undiluted");
INSERT INTO PRODUCT VALUES (1725, 9,  "Orange juice, frozen concentrate, diluted");
INSERT INTO PRODUCT VALUES (1726, 9,  "Tangerine (mandarin), canned, juice pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1727, 9,  "Tangerine (mandarin), canned, light syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1728, 9,  "Peach, raw");
INSERT INTO PRODUCT VALUES (1729, 9,  "Peach, canned halves or slices, water pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1730, 9,  "Peach, canned halves or slices, light syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1731, 9,  "Pear, raw, with skin");
INSERT INTO PRODUCT VALUES (1732, 9,  "Pear, canned halves, water pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1733, 9,  "Pear, canned halves, light syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1734, 9,  "Pineapple, raw");
INSERT INTO PRODUCT VALUES (1735, 9,  "Pineapple, canned, water pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1736, 9,  "Pineapple, canned, juice pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1737, 9,  "Pineapple, canned, light syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1738, 9,  "Pineapple, canned heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1739, 9,  "Pineapple, canned, extra heavy syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1740, 9,  "Plum, raw");
INSERT INTO PRODUCT VALUES (1741, 9,  "Plum, canned, purple, light syrup pack, solids and liquid");
INSERT INTO PRODUCT VALUES (1742, 9,  "Prune, dried, uncooked");
INSERT INTO PRODUCT VALUES (1743, 9,  "Prune, dried, cooked, no added sugar");
INSERT INTO PRODUCT VALUES (1744, 9,  "Raisin, golden seedless");
INSERT INTO PRODUCT VALUES (1745, 9,  "Raisin, seedless (sultana)");
INSERT INTO PRODUCT VALUES (1746, 9,  "Raisin, seeded");
INSERT INTO PRODUCT VALUES (1747, 9,  "Raspberry, raw");
INSERT INTO PRODUCT VALUES (1748, 9,  "Rhubarb, raw");
INSERT INTO PRODUCT VALUES (1749, 9,  "Strawberry, raw");
INSERT INTO PRODUCT VALUES (1750, 9,  "Strawberry, frozen, unsweetened");
INSERT INTO PRODUCT VALUES (1751, 9,  "Haw, scarlet, meat and skin, raw");
INSERT INTO PRODUCT VALUES (1752, 9,  "Apple juice, canned or bottled, added vitamin C");
INSERT INTO PRODUCT VALUES (1753, 9,  "Apple juice, frozen concentrate, undiluted, added vitamin C");
INSERT INTO PRODUCT VALUES (1754, 9,  "Apple juice, frozen concentrate, diluted, added vitamin C");
INSERT INTO PRODUCT VALUES (4845, 9,  "Mangosteen, canned, syrup pack");
INSERT INTO PRODUCT VALUES (4846, 9,  "Jackfruit, canned, syrup pack");
INSERT INTO PRODUCT VALUES (4847, 9,  "Durian, raw or frozen");
INSERT INTO PRODUCT VALUES (4878, 9,  "Rambutan, canned, syrup pack");
INSERT INTO PRODUCT VALUES (4879, 9,  "Prune puree");
INSERT INTO PRODUCT VALUES (5282, 9,  "Abiyuch, raw");
INSERT INTO PRODUCT VALUES (5283, 9,  "Rowal, raw");
INSERT INTO PRODUCT VALUES (5389, 9,  "Blackberry juice, canned");
INSERT INTO PRODUCT VALUES (5390, 9,  "Cranberry, dried, sweetened");
INSERT INTO PRODUCT VALUES (5391, 9,  "Olive, pickled, canned or bottled, green");
INSERT INTO PRODUCT VALUES (5393, 9,  "Fruit cocktail (peach, pear, apricot, pineapple, cherry, grape), canned, heavy syrup, drained");
INSERT INTO PRODUCT VALUES (5394, 9,  "Pineapple, canned, juice pack, drained");
INSERT INTO PRODUCT VALUES (5395, 9,  "Apricot, canned, heavy syrup, drained");
INSERT INTO PRODUCT VALUES (5396, 9,  "Cherry, sweet, canned, heavy syrup, drained");
INSERT INTO PRODUCT VALUES (5397, 9,  "Peach, canned, heavy syrup, drained");
INSERT INTO PRODUCT VALUES (5398, 9,  "Pear, canned, heavy syrup, drained");
INSERT INTO PRODUCT VALUES (5399, 9,  "Plum, canned, heavy syrup, drained");
INSERT INTO PRODUCT VALUES (5400, 9,  "Tangerine, (mandarin), canned, juice pack, drained");
INSERT INTO PRODUCT VALUES (5401, 9,  "Date, medjool");
INSERT INTO PRODUCT VALUES (5403, 9,  "Pineapple, raw, traditional varieties");
INSERT INTO PRODUCT VALUES (5404, 9,  "Pineapple, raw, extra sweet variety");
INSERT INTO PRODUCT VALUES (5472, 9,  "Orange-strawberry-banana juice");
INSERT INTO PRODUCT VALUES (5593, 9,  "Cranberry juice, unsweetened");
INSERT INTO PRODUCT VALUES (5938, 9,  "Black crowberry (curlewberry), native");
INSERT INTO PRODUCT VALUES (5939, 9,  "Cloudberry (bakeapple), native");
INSERT INTO PRODUCT VALUES (5956, 9,  "Clementine, raw");
INSERT INTO PRODUCT VALUES (6203, 9,  "Orange juice, chilled, includes from concentrate, fortified with added calcium and vitamin D");
INSERT INTO PRODUCT VALUES (6204, 9,  "Guava, nectar, canned");
INSERT INTO PRODUCT VALUES (6205, 9,  "Mango,  nectar, canned");
INSERT INTO PRODUCT VALUES (6259, 9,  "Salmonberry, raw");
INSERT INTO PRODUCT VALUES (6260, 9,  "Chokecherry, raw, pitted");
INSERT INTO PRODUCT VALUES (501549, 9,  "Rose hips, wild, native");
INSERT INTO PRODUCT VALUES (501597, 9,  "Blackberry, wild, raw");
INSERT INTO PRODUCT VALUES (501599, 9,  "Blueberry, wild, raw");
INSERT INTO PRODUCT VALUES (501634, 9,  "Cranberry (lingonberry), wild, raw");
INSERT INTO PRODUCT VALUES (501658, 9,  "Grapefruit juice, pink, raw");
INSERT INTO PRODUCT VALUES (501662, 9,  "Huckleberries, raw");
INSERT INTO PRODUCT VALUES (501751, 9,  "Raspberry, wild, raw");
INSERT INTO PRODUCT VALUES (501861, 9,  "Fruit salad, tropical (pineapple, red and yellow papaya), canned, juice pack, solids and liquid");
INSERT INTO PRODUCT VALUES (501882, 9,  "Blueberry, wild, frozen");
INSERT INTO PRODUCT VALUES (501883, 9,  "Grape juice, canned or bottled, unsweetened, with added vitamin C");
INSERT INTO PRODUCT VALUES (501884, 9,  "Pomegranate juice, ready-to-drink");
INSERT INTO PRODUCT VALUES (501885, 9,  "Juice, apple and grape, with added vitamin C");
INSERT INTO PRODUCT VALUES (502016, 9,  "Kiwi fruit, gold, raw");
INSERT INTO PRODUCT VALUES (502135, 9,  "Plantain, green, fried");
INSERT INTO PRODUCT VALUES (502145, 9,  "Papaya, canned, heavy syrup pack, drained");
INSERT INTO PRODUCT VALUES (502223, 9,  "Melon, horned");
INSERT INTO PRODUCT VALUES (502253, 9,  "Orange pineapple juice");
INSERT INTO PRODUCT VALUES (502341, 9,  "Pear, Bartlett, raw");
INSERT INTO PRODUCT VALUES (502342, 9,  "Apple, Golden Delicious, raw, with skin");
INSERT INTO PRODUCT VALUES (502427, 9,  "Cherries, tart, dried, sweetened");
INSERT INTO PRODUCT VALUES (502428, 9,  "Blueberry, dried, sweetened");
INSERT INTO PRODUCT VALUES (502429, 9,  "Cherry, sour, canned, water pack, drained");
INSERT INTO PRODUCT VALUES (502430, 9,  "Pear, red anjou, raw");
INSERT INTO PRODUCT VALUES (502431, 9,  "Pear, bosc, raw");
INSERT INTO PRODUCT VALUES (502432, 9,  "Pear, green anjou, raw");
INSERT INTO PRODUCT VALUES (502433, 9,  "Apple, Red Delicious, raw, with skin");
INSERT INTO PRODUCT VALUES (502434, 9,  "Apple, Granny Smith, raw, with skin");
INSERT INTO PRODUCT VALUES (502435, 9,  "Apple, Gala, raw, with skin");
INSERT INTO PRODUCT VALUES (502436, 9,  "Apple, Fuji, raw, with skin");
INSERT INTO PRODUCT VALUES (502695, 9,  "Apple juice, canned or bottled, unsweetened, calcium and Vitamin C and D added");
INSERT INTO PRODUCT VALUES (502700, 9,  "Orange juice, frozen concentrate, undiluted, with added calcium and Vitamin D");
INSERT INTO PRODUCT VALUES (502701, 9,  "Raspberry, frozen, unsweetened");
INSERT INTO PRODUCT VALUES (503365, 9,  "Orange juice, frozen concentrate, diluted, with added calcium and Vitamin D");