--------- Drop Tables -------

DROP TABLE PRODUCER_PRODUCT;
DROP TABLE PRODUCT;
DROP TABLE PDT_GROUP;
DROP TABLE USER_ADMIN;
DROP PRODUCER_PROFILE;

---------Create Tables -------

CREATE TABLE PDT_GROUP (
    GROUP_ID INTEGER NOT NULL,
    GROUP_NAME TEXT,
    PRIMARY KEY (GROUP_ID)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID INTEGER NOT NULL,
	GROUP_ID INTEGER NOT NULL,
    PRODUCT_DESCRIPTION TEXT,
    PRIMARY KEY (PRODUCT_ID, GROUP_ID),
	FOREIGN KEY (GROUP_ID) REFERENCES PDT_GROUP(GROUP_ID)
);

CREATE TABLE PRODUCER_PRODUCT (
    PRODUCER_ID INTEGER NOT NULL,
    GROUP_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    PRODUCT_DESCRIPTION TEXT NOT NULL,
    SCIENTIFIC_NAME TEXT,
    PRIMARY KEY (PRODUCER_ID),
    FOREIGN KEY (PRODUCER_ID) REFERENCES USER_ADMIN(USER_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES PDT_GROUP(GROUP_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE USER_ADMIN (
    USER_ID INTEGER NOT NULL,
    USER_NAME TEXT,
    PASSWORD TEXT,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE PRODUCER_PROFILE (
    PRODUCER_ID INTEGER NOT NULL,
    COMPANY_NAME TEXT,
    CONTACT_NAME TEXT,
    STREET TEXT,
    CITY TEXT,
    PROV_STATE TEXT,
    COUNTRY TEXT,
    PCODE TEXT,
    PHONE TEXT,
    CONTACT_EMAIL TEXT,
    WEBSITE TEXT,
    GMAP_PLUS_CODE TEXT,
    PRIMARY KEY (PRODUCER_ID),
    FOREIGN KEY (PRODUCER_ID) REFERENCES USER_ADMIN(USER_ID)
);
